# Generated by Django 5.1.3 on 2024-11-29 11:00

import django.core.validators
import django.db.models.deletion
import projects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("settings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=4, verbose_name="申报年度")),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="项目名称"
                    ),
                ),
                (
                    "beg_year",
                    models.CharField(
                        blank=True, max_length=4, null=True, verbose_name="起始年份"
                    ),
                ),
                (
                    "end_year",
                    models.CharField(
                        blank=True, max_length=4, null=True, verbose_name="结束年份"
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="研究方向"
                    ),
                ),
                (
                    "purpose",
                    models.TextField(
                        blank=True, null=True, verbose_name="研究的目的和意义"
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="研究内容"),
                ),
                (
                    "progress",
                    models.TextField(blank=True, null=True, verbose_name="研究进度"),
                ),
                (
                    "result",
                    models.TextField(blank=True, null=True, verbose_name="预期成果"),
                ),
                (
                    "budget",
                    models.TextField(blank=True, null=True, verbose_name=" 经费预算"),
                ),
                (
                    "opinion",
                    models.TextField(blank=True, null=True, verbose_name=" 审核意见"),
                ),
                (
                    "application_attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=projects.models.get_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["doc", "docx", "pdf"]
                            )
                        ],
                        verbose_name="项目申报附件",
                    ),
                ),
                (
                    "inspection_attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=projects.models.get_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["doc", "docx", "pdf"]
                            )
                        ],
                        verbose_name="中期检查附件",
                    ),
                ),
                (
                    "conclusion_attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=projects.models.get_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["doc", "docx", "pdf"]
                            )
                        ],
                        verbose_name="项目结题附件",
                    ),
                ),
                (
                    "application_opinion",
                    models.TextField(
                        blank=True, null=True, verbose_name="申报审核意见"
                    ),
                ),
                (
                    "application_is_agreed",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="是否同意申报"
                    ),
                ),
                (
                    "inspection_opinion",
                    models.TextField(
                        blank=True, null=True, verbose_name="中期检查意见"
                    ),
                ),
                (
                    "inspection_is_agreed",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="检查是否合格"
                    ),
                ),
                (
                    "conclusion_opinion",
                    models.TextField(
                        blank=True, null=True, verbose_name="结题审核意见"
                    ),
                ),
                (
                    "conclusion_is_agreed",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="是否允许结题"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="project_applicant",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请者",
                    ),
                ),
                (
                    "application_panelist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="project_application_panelist",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="项目申报评审专家",
                    ),
                ),
                (
                    "conclusion_panelist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="project_conclusion_panelist",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="项目结题评审专家",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="project_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "inspection_panelist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="project_inspection_panelist",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="中期检查评审专家",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="settings.subject",
                        verbose_name="所属学科",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="accounts.team",
                        verbose_name="评审组",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="settings.type",
                        verbose_name="研究类型",
                    ),
                ),
                (
                    "updator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="project_updator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目信息",
                "verbose_name_plural": "项目信息",
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="姓名"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="联系电话"
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="研究领域"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="member_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "degree",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="member_degree",
                        to="settings.degree",
                        verbose_name="最高学位",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="member_department",
                        to="settings.department",
                        verbose_name="所属单位",
                    ),
                ),
                (
                    "education",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="member_education",
                        to="settings.education",
                        verbose_name="最高学历",
                    ),
                ),
                (
                    "gender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="member_gender",
                        to="settings.gender",
                        verbose_name="性别",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="projects.information",
                        verbose_name="所属项目",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="member_subject",
                        to="settings.subject",
                        verbose_name="所在学科",
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="member_title",
                        to="settings.title",
                        verbose_name="职称",
                    ),
                ),
                (
                    "updator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="member_updator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目组成员",
                "verbose_name_plural": "项目组成员",
            },
        ),
    ]
