# Generated by Django 5.1.3 on 2024-11-29 17:39

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="information",
            name="budget",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name=" 经费预算"
            ),
        ),
    ]
