# Generated by Django 5.1.3 on 2024-11-29 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_information_department_is_agreed_and_more"),
        ("settings", "0003_rename_is_opend_setting_is_opened"),
    ]

    operations = [
        migrations.AddField(
            model_name="information",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="settings.series",
                verbose_name="项目系列",
            ),
        ),
    ]
