# Generated by Django 5.1.3 on 2024-12-01 01:57

import django.core.validators
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_information_series"),
    ]

    operations = [
        migrations.AlterField(
            model_name="information",
            name="application_attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=projects.models.get_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
                verbose_name="项目申报附件",
            ),
        ),
        migrations.AlterField(
            model_name="information",
            name="conclusion_attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=projects.models.get_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
                verbose_name="项目结题附件",
            ),
        ),
        migrations.AlterField(
            model_name="information",
            name="inspection_attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=projects.models.get_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
                verbose_name="中期检查附件",
            ),
        ),
    ]
