# Generated by Django 5.1.3 on 2024-12-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_alter_information_beg_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="information",
            name="is_confirmed",
            field=models.BooleanField(default=False, verbose_name="是否已经确认"),
        ),
    ]
