# Generated by Django 5.1.3 on 2024-11-12 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("settings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="名称")),
            ],
            options={
                "verbose_name": "角色",
                "verbose_name_plural": "角色",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="姓名"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="联系电话"
                    ),
                ),
                (
                    "idnumber",
                    models.CharField(
                        blank=True,
                        max_length=18,
                        null=True,
                        unique=True,
                        verbose_name="证件号码",
                    ),
                ),
                (
                    "college",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="所在院校"
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="研究领域"
                    ),
                ),
                (
                    "account",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="银行卡号",
                    ),
                ),
                (
                    "bank",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="开户行信息"
                    ),
                ),
                (
                    "bankno",
                    models.CharField(
                        blank=True,
                        max_length=12,
                        null=True,
                        verbose_name="开户行行联号",
                    ),
                ),
                (
                    "is_enable",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="profile_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "degree",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="profile_degree",
                        to="settings.degree",
                        verbose_name="最高学位",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="profile_department",
                        to="settings.department",
                        verbose_name="所属单位",
                    ),
                ),
                (
                    "education",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="profile_education",
                        to="settings.education",
                        verbose_name="最高学历",
                    ),
                ),
                (
                    "gender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="profile_gender",
                        to="settings.gender",
                        verbose_name="性别",
                    ),
                ),
                (
                    "idtype",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="profile_idtype",
                        to="settings.idtype",
                        verbose_name="证件类型",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="profile_subject",
                        to="settings.subject",
                        verbose_name="所在学科",
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="profile_title",
                        to="settings.title",
                        verbose_name="职称",
                    ),
                ),
                (
                    "updator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="profile_updator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="accounts.role",
                        verbose_name="角色",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户资料",
                "verbose_name_plural": "用户资料",
            },
        ),
    ]
