# Generated by Django 5.1.3 on 2024-12-01 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_role_profile_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="is_enable",
        ),
    ]
