# Generated by Django 5.1.3 on 2024-12-27 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_profile_is_enable"),
        ("settings", "0003_rename_is_opend_setting_is_opened"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="idtype",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="profile_idtype",
                to="settings.idtype",
                verbose_name="证件类型",
            ),
        ),
    ]
