# Generated by Django 5.1.3 on 2024-11-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="setting",
            name="is_opend",
            field=models.BooleanField(default=False, verbose_name="是否开启"),
        ),
    ]
