# Generated by Django 5.1.3 on 2024-11-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_confirmed",
            field=models.BooleanField(default=False, verbose_name="是否已经确认"),
        ),
    ]
